package com.ita.edu.teachua.utils.jdbc.entity;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;

import java.util.ArrayList;
import java.util.List;

@AllArgsConstructor
@Setter
@Getter
public class ExcelCenterEntity {

    public static final String SELECT_ALL = "SELECT * FROM excel_center_entity ORDER BY autogenerated_id;";

    private Long autogeneratedId;
    private String address;
    private Long centerExternalId;
    private String cityName;
    private String coordinates;
    private String description;
    private String district;
    private String name;
    private String phone;
    private String station;
    private String webContact;

    public ExcelCenterEntity() {
        this.autogeneratedId = 0L;
        this.address = null;
        this.centerExternalId = 0L;
        this.cityName = null;
        this.coordinates = null;
        this.description = null;
        this.district = null;
        this.name = null;
        this.phone = null;
        this.station = null;
        this.webContact = null;
    }

    public static ExcelCenterEntity getExcelCenterEntity(List<String> row) {
        ExcelCenterEntity excelCenterEntity = new ExcelCenterEntity();
        excelCenterEntity.setAutogeneratedId(Long.parseLong(row.get(0)));
        excelCenterEntity.setAddress(row.get(1));
        excelCenterEntity.setCenterExternalId(Long.parseLong(row.get(2)));
        excelCenterEntity.setCityName(row.get(3));
        excelCenterEntity.setCoordinates(row.get(4));
        excelCenterEntity.setDescription(row.get(5));
        excelCenterEntity.setDistrict(row.get(6));
        excelCenterEntity.setName(row.get(7));
        excelCenterEntity.setPhone(row.get(8));
        excelCenterEntity.setStation(row.get(9));
        excelCenterEntity.setWebContact(row.get(10));

        return excelCenterEntity;
    }

    public static List<ExcelCenterEntity> getExcelCenterEntities(List<List<String>> rows) {
        List<ExcelCenterEntity> excelCenterEntities = new ArrayList<>();
        for (List<String> row : rows) {
            excelCenterEntities.add(getExcelCenterEntity(row));
        }
        return excelCenterEntities;
    }

    @Override
    public String toString() {
        return "ExcelCenterEntity{" +
                "autogeneratedId=" + autogeneratedId +
                ", address='" + address + '\'' +
                ", centerExternalId=" + centerExternalId +
                ", cityName='" + cityName + '\'' +
                ", coordinates='" + coordinates + '\'' +
                ", description='" + description + '\'' +
                ", district='" + district + '\'' +
                ", name='" + name + '\'' +
                ", phone='" + phone + '\'' +
                ", station='" + station + '\'' +
                ", webContact='" + webContact + '\'' +
                '}';
    }
}
